export const canvas = document.querySelector("#game");

export const hud = {
  wave: document.querySelector("#waveText"),
  time: document.querySelector("#timeText"),
  hp: document.querySelector("#hpFill"),
  hpText: document.querySelector("#hpText"),
  gold: document.querySelector("#goldText"),
  kills: document.querySelector("#killText"),
  shopGold: document.querySelector("#shopGoldText"),
  shopContinue: document.querySelector("#shopContinueBtn"),
  hitFlash: document.querySelector("#hitFlash"),
  shop: document.querySelector("#shop"),
  offers: document.querySelector("#offers"),
  gearInventory: document.querySelector("#gearInventory"),
  starterPick: document.querySelector("#starterPick"),
  starterOffers: document.querySelector("#starterOffers"),
  gameOver: document.querySelector("#gameOver"),
  result: document.querySelector("#resultText"),
  restart: document.querySelector("#restartBtn"),
  touchControls: document.querySelector("#touchControls"),
  moveStick: document.querySelector("#moveStick"),
  moveThumb: document.querySelector("#moveThumb"),
  pauseBtn: document.querySelector("#pauseBtn"),
  pauseMenu: document.querySelector("#pauseMenu"),
  resumeBtn: document.querySelector("#resumeBtn"),
  pauseDebugBtn: document.querySelector("#pauseDebugBtn"),
  pauseRestartBtn: document.querySelector("#pauseRestartBtn"),
  debugPanel: document.querySelector("#debugPanel"),
  dbgClose: document.querySelector("#dbgClose"),
  dbgWeaponSel: document.querySelector("#dbgWeaponSel"),
  dbgWeaponEquip: document.querySelector("#dbgWeaponEquip"),
  dbgAttSel: document.querySelector("#dbgAttSel"),
  dbgAttWeapon: document.querySelector("#dbgAttWeapon"),
  dbgAttApply: document.querySelector("#dbgAttApply"),
  dbgEnemySel: document.querySelector("#dbgEnemySel"),
  dbgEnemySpawn: document.querySelector("#dbgEnemySpawn"),
  dbgHeal: document.querySelector("#dbgHeal"),
  dbgKillAll: document.querySelector("#dbgKillAll"),
  dbgInvuln: document.querySelector("#dbgInvuln"),
  dbgShop: document.querySelector("#dbgShop"),
  dbgNextWave: document.querySelector("#dbgNextWave"),
};
