export const canvas = document.querySelector("#game");

export const hud = {
  wave: document.querySelector("#waveText"),
  time: document.querySelector("#timeText"),
  hp: document.querySelector("#hpFill"),
  hpText: document.querySelector("#hpText"),
  cash: document.querySelector("#cashText"),
  kills: document.querySelector("#killText"),
  hitFlash: document.querySelector("#hitFlash"),
  shop: document.querySelector("#shop"),
  offers: document.querySelector("#offers"),
  shopCash: document.querySelector("#shopCash"),
  gearInventory: document.querySelector("#gearInventory"),
  reroll: document.querySelector("#rerollBtn"),
  nextWave: document.querySelector("#nextWaveBtn"),
  starterPick: document.querySelector("#starterPick"),
  starterOffers: document.querySelector("#starterOffers"),
  gameOver: document.querySelector("#gameOver"),
  result: document.querySelector("#resultText"),
  restart: document.querySelector("#restartBtn"),
  touchControls: document.querySelector("#touchControls"),
  moveStick: document.querySelector("#moveStick"),
  moveThumb: document.querySelector("#moveThumb"),
  debugPanel: document.querySelector("#debugPanel"),
  dbgWeaponSel: document.querySelector("#dbgWeaponSel"),
  dbgWeaponEquip: document.querySelector("#dbgWeaponEquip"),
  dbgAttSel: document.querySelector("#dbgAttSel"),
  dbgAttRarity: document.querySelector("#dbgAttRarity"),
  dbgAttWeapon: document.querySelector("#dbgAttWeapon"),
  dbgAttApply: document.querySelector("#dbgAttApply"),
  dbgEnemySel: document.querySelector("#dbgEnemySel"),
  dbgEnemySpawn: document.querySelector("#dbgEnemySpawn"),
  dbgMoney: document.querySelector("#dbgMoney"),
  dbgHeal: document.querySelector("#dbgHeal"),
  dbgKillAll: document.querySelector("#dbgKillAll"),
  dbgInvuln: document.querySelector("#dbgInvuln"),
  dbgShop: document.querySelector("#dbgShop"),
  dbgNextWave: document.querySelector("#dbgNextWave"),
};
