import { SPECIAL_REQUIREMENTS, STONE_TEXT } from "./stoneDefinitions.js";
// Functional node catalog and build recipes.
const BASE_SKILLS = [
  {
    id: "A01",
    name: "穿孔石",
    family: "A",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "直線を貫く細い石を自動発射。",
  },
  {
    id: "A02",
    name: "散弾核",
    family: "A",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "扇状に石を発射。近いほど多数が当たる。",
  },
  {
    id: "A03",
    name: "石弾倉",
    family: "A",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "一定数を撃って自動再装填する連射武装。弾は無料で再生。",
  },
  {
    id: "A04",
    name: "列狙い",
    family: "A",
    requires_all: ["A01"],
    major: false,
    cost: 25,
    effect: "最寄りではなく複数を貫ける射線を優先。",
  },
  {
    id: "A05",
    name: "後方射撃",
    family: "A",
    requires_all: ["A02"],
    major: false,
    cost: 25,
    effect: "散弾の一部を後方へ割り振る。総弾威力は配分する。",
  },
  {
    id: "A06",
    name: "最終弾",
    family: "A",
    requires_all: ["A03"],
    major: false,
    cost: 25,
    effect: "弾倉の最後の一発が円形の追加射撃を起こす。",
  },
  {
    id: "A07",
    name: "孤立照準",
    family: "A",
    requires_all: ["A04"],
    major: false,
    cost: 60,
    effect: "近くに仲間がいない敵へ貫通弾の威力増。",
  },
  {
    id: "A08",
    name: "収束散弾",
    family: "A",
    requires_all: ["A05"],
    major: false,
    cost: 60,
    effect: "散弾角を狭め、全弾を同じ対象へ当てやすくする。",
  },
  {
    id: "A09",
    name: "小弾倉",
    family: "A",
    requires_all: ["A06"],
    major: false,
    cost: 60,
    effect: "弾数を減らし再装填を速める。弾切れ効果を頻発させる。",
  },
  {
    id: "A10",
    name: "地平貫き",
    family: "A",
    requires_all: ["A07"],
    major: true,
    cost: 140,
    effect: "射程端へ向けて太くなる重い貫通波に変形。連射低下。",
  },
  {
    id: "A11",
    name: "零距離破城",
    family: "A",
    requires_all: ["A08"],
    major: true,
    cost: 140,
    effect: "近距離で同時に当てた散弾数に応じて装甲破壊。",
  },
  {
    id: "A12",
    name: "装填砲",
    family: "A",
    requires_all: ["A09"],
    major: true,
    cost: 140,
    effect: "自動装填の完了時に強い一撃。小弾倉と高速周期を作る。",
  },
  {
    id: "B01",
    name: "跳石",
    family: "B",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "敵から近くの別の敵へ跳ねる石を撃つ。壁不要。",
  },
  {
    id: "B02",
    name: "帰還刃",
    family: "B",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "出て戻る石刃。復路は現在の自分の位置を目指す。",
  },
  {
    id: "B03",
    name: "破砕石",
    family: "B",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "命中位置で小さく爆発する石を撃つ。",
  },
  {
    id: "B04",
    name: "遠跳び",
    family: "B",
    requires_all: ["B01"],
    major: false,
    cost: 25,
    effect: "跳ぶ先の探索半径を広げ、離れた群れへ渡る。",
  },
  {
    id: "B05",
    name: "復路研磨",
    family: "B",
    requires_all: ["B02"],
    major: false,
    cost: 25,
    effect: "往路で当てた敵への復路ダメージ増。",
  },
  {
    id: "B06",
    name: "残片",
    family: "B",
    requires_all: ["B03"],
    major: false,
    cost: 25,
    effect: "撃破した爆心から破片弾。",
  },
  {
    id: "B07",
    name: "往復反射",
    family: "B",
    requires_all: ["B04"],
    major: false,
    cost: 60,
    effect: "2回目以降に同一敵へ戻れるが、再命中間隔と回数制限あり。",
  },
  {
    id: "B08",
    name: "帰還受け",
    family: "B",
    requires_all: ["B05"],
    major: false,
    cost: 60,
    effect: "戻った刃を受けた直後、次の発射が速くなる。",
  },
  {
    id: "B09",
    name: "時限破裂",
    family: "B",
    requires_all: ["B06"],
    major: false,
    cost: 60,
    effect: "爆発を短時間遅らせる代わりに広げる。",
  },
  {
    id: "B10",
    name: "連鎖破城",
    family: "B",
    requires_all: ["B07"],
    major: true,
    cost: 140,
    effect: "最後の跳弾で爆発。跳んだ回数で半径が増す。",
  },
  {
    id: "B11",
    name: "折返し嵐",
    family: "B",
    requires_all: ["B08"],
    major: true,
    cost: 140,
    effect: "帰還地点から短い逆向きの刃を追加。再帰しない。",
  },
  {
    id: "B12",
    name: "残響爆心",
    family: "B",
    requires_all: ["B09"],
    major: true,
    cost: 140,
    effect: "同じ場所に時間差の2回目の爆発。敵を留めると有効。",
  },
  {
    id: "C01",
    name: "衛星石",
    family: "C",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "一定半径で石が周回。",
  },
  {
    id: "C02",
    name: "岩衣",
    family: "C",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "身の回りを覆う短距離の周期攻撃。",
  },
  {
    id: "C03",
    name: "引力核",
    family: "C",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "周期的に敵を自分の少し前へ引き寄せる。",
  },
  {
    id: "C04",
    name: "外周軌道",
    family: "C",
    requires_all: ["C01"],
    major: false,
    cost: 25,
    effect: "周回を遠くにし、中心付近に空白を作る。",
  },
  {
    id: "C05",
    name: "棘の縁",
    family: "C",
    requires_all: ["C02"],
    major: false,
    cost: 25,
    effect: "岩衣が接触した敵に短時間の刺傷。",
  },
  {
    id: "C06",
    name: "重力標",
    family: "C",
    requires_all: ["C03"],
    major: false,
    cost: 25,
    effect: "引力の中心を最寄りの敵の位置へ移す。",
  },
  {
    id: "C07",
    name: "偏心軌道",
    family: "C",
    requires_all: ["C04"],
    major: false,
    cost: 60,
    effect: "周回半径が周期的に伸縮する。",
  },
  {
    id: "C08",
    name: "接近圧",
    family: "C",
    requires_all: ["C05"],
    major: false,
    cost: 60,
    effect: "近距離にいる時間に応じて敵への圧力が増す。離れると減る。",
  },
  {
    id: "C09",
    name: "圧縮",
    family: "C",
    requires_all: ["C06"],
    major: false,
    cost: 60,
    effect: "引き寄せた敵が重なると、蓄積圧力による単発攻撃。",
  },
  {
    id: "C10",
    name: "二重公転",
    family: "C",
    requires_all: ["C07"],
    major: true,
    cost: 140,
    effect: "内側に逆回転の小さな軌道を追加。",
  },
  {
    id: "C11",
    name: "破城鎧",
    family: "C",
    requires_all: ["C08"],
    major: true,
    cost: 140,
    effect: "防壁を失ったとき岩衣が短時間拡大し敵を押し返す。",
  },
  {
    id: "C12",
    name: "崩壊星",
    family: "C",
    requires_all: ["C09"],
    major: true,
    cost: 140,
    effect: "引力の終了地点で圧縮ダメージを解放。",
  },
  {
    id: "D01",
    name: "石砲台",
    family: "D",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "少し停止すると足元に砲台を配置。寿命と設置数上限あり。",
  },
  {
    id: "D02",
    name: "足跡地雷",
    family: "D",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "移動距離ごとに接近起爆の地雷を残す。",
  },
  {
    id: "D03",
    name: "震域",
    family: "D",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "一定間隔で足元へ持続する地震領域を残す。",
  },
  {
    id: "D04",
    name: "照準杭",
    family: "D",
    requires_all: ["D01"],
    major: false,
    cost: 25,
    effect: "砲台同士が同じ強敵へ集中射撃する。",
  },
  {
    id: "D05",
    name: "連結導火線",
    family: "D",
    requires_all: ["D02"],
    major: false,
    cost: 25,
    effect: "爆発が近くの地雷を順に起爆。",
  },
  {
    id: "D06",
    name: "固着",
    family: "D",
    requires_all: ["D03"],
    major: false,
    cost: 25,
    effect: "震域内の敵の移動を遅くする。",
  },
  {
    id: "D07",
    name: "移動架台",
    family: "D",
    requires_all: ["D04"],
    major: false,
    cost: 60,
    effect: "砲台がゆっくり追従する。",
  },
  {
    id: "D08",
    name: "育つ地雷",
    family: "D",
    requires_all: ["D05"],
    major: false,
    cost: 60,
    effect: "起爆まで待った地雷の威力が上がる。上限あり。",
  },
  {
    id: "D09",
    name: "重ね震い",
    family: "D",
    requires_all: ["D06"],
    major: false,
    cost: 60,
    effect: "自分の震域が重なる場所に周期的な強い脈動。",
  },
  {
    id: "D10",
    name: "砲列",
    family: "D",
    requires_all: ["D07"],
    major: true,
    cost: 140,
    effect: "新しい砲台が近くの既存砲台と射線を分担し、横に並ぶ。",
  },
  {
    id: "D11",
    name: "雷管群",
    family: "D",
    requires_all: ["D08"],
    major: true,
    cost: 140,
    effect: "大物が近くを通ると複数の地雷が時間差で集中起爆。",
  },
  {
    id: "D12",
    name: "大地共鳴",
    family: "D",
    requires_all: ["D09"],
    major: true,
    cost: 140,
    effect: "震域同士をつなぐ線にも攻撃判定。線の長さ上限あり。",
  },
  {
    id: "E01",
    name: "石の使い魔",
    family: "E",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "敵を探して体当たりする使い魔を周期召喚。",
  },
  {
    id: "E02",
    name: "岩の守護者",
    family: "E",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "自分の近くで敵を押し返す守護者を召喚。",
  },
  {
    id: "E03",
    name: "亡響",
    family: "E",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "自分の撃破から短命の追尾霊。単体への累積命中でも低頻度に発動。",
  },
  {
    id: "E04",
    name: "遠征命令",
    family: "E",
    requires_all: ["E01"],
    major: false,
    cost: 25,
    effect: "使い魔が遠い強敵を優先。自分の周囲は手薄になる。",
  },
  {
    id: "E05",
    name: "身代わり",
    family: "E",
    requires_all: ["E02"],
    major: false,
    cost: 25,
    effect: "守護者が一度だけ接触攻撃を肩代わりし、寿命を消費。",
  },
  {
    id: "E06",
    name: "継承印",
    family: "E",
    requires_all: ["E03"],
    major: false,
    cost: 25,
    effect: "亡響が倒した敵からも次の亡響。ただし世代・同時数に制限。",
  },
  {
    id: "E07",
    name: "帰還補修",
    family: "E",
    requires_all: ["E04"],
    major: false,
    cost: 60,
    effect: "使い魔が帰還すると次の個体が短い防壁を持つ。",
  },
  {
    id: "E08",
    name: "守護反撃",
    family: "E",
    requires_all: ["E05"],
    major: false,
    cost: 60,
    effect: "身代わりが起きると守護者が扇状に反撃。",
  },
  {
    id: "E09",
    name: "共食い",
    family: "E",
    requires_all: ["E06"],
    major: false,
    cost: 60,
    effect: "同時上限時、新しい亡響を既存の1体へ吸収して強化。",
  },
  {
    id: "E10",
    name: "使い捨て兵団",
    family: "E",
    requires_all: ["E07"],
    major: true,
    cost: 140,
    effect: "使い魔が帰還せず寿命終了で爆発。帰還補修は消滅前の防壁へ置換。",
  },
  {
    id: "E11",
    name: "巨像",
    family: "E",
    requires_all: ["E08"],
    major: true,
    cost: 140,
    effect: "守護者を一体の大きな近接召喚へ統合。数の利点を失う。",
  },
  {
    id: "E12",
    name: "群体王",
    family: "E",
    requires_all: ["E09"],
    major: true,
    cost: 140,
    effect: "吸収した亡響が一定数で一体の強い追尾霊になる。",
  },
  {
    id: "F01",
    name: "火種",
    family: "F",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "武器命中で燃焼を付ける。小さな継続ダメージ。",
  },
  {
    id: "F02",
    name: "蓄熱石",
    family: "F",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "範囲内に敵がいない間に溜まり、接近した敵へ強い熱撃。",
  },
  {
    id: "F03",
    name: "火の足跡",
    family: "F",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "移動距離で短時間の燃焼床を残す。",
  },
  {
    id: "F04",
    name: "延焼",
    family: "F",
    requires_all: ["F01"],
    major: false,
    cost: 25,
    effect: "燃える敵から隣の敵へ低頻度で燃焼を渡す。",
  },
  {
    id: "F05",
    name: "保温",
    family: "F",
    requires_all: ["F02"],
    major: false,
    cost: 25,
    effect: "熱撃後に熱の一部を残し、短い連続接近に対応。",
  },
  {
    id: "F06",
    name: "焦土",
    family: "F",
    requires_all: ["F03"],
    major: false,
    cost: 25,
    effect: "燃焼床を踏む間、燃焼の残り時間を更新。",
  },
  {
    id: "F07",
    name: "炭化",
    family: "F",
    requires_all: ["F04"],
    major: false,
    cost: 60,
    effect: "燃焼時間の長い敵に通常命中の追加ダメージ。",
  },
  {
    id: "F08",
    name: "過熱",
    family: "F",
    requires_all: ["F05"],
    major: false,
    cost: 60,
    effect: "最大蓄熱まで待つと熱撃が扇状になる。",
  },
  {
    id: "F09",
    name: "灰の道",
    family: "F",
    requires_all: ["F06"],
    major: false,
    cost: 60,
    effect: "燃焼床が消えた後、短く敵を鈍らせる灰を残す。",
  },
  {
    id: "F10",
    name: "爆燃",
    family: "F",
    requires_all: ["F07"],
    major: true,
    cost: 140,
    effect: "燃焼中の敵の撃破で周囲に爆発。ボスは一定蓄積でも小さく発動。",
  },
  {
    id: "F11",
    name: "太陽核",
    family: "F",
    requires_all: ["F08"],
    major: true,
    cost: 140,
    effect: "溜めた熱撃を自分中心の一撃に変え、再蓄熱は遅くなる。",
  },
  {
    id: "F12",
    name: "火環",
    family: "F",
    requires_all: ["F09"],
    major: true,
    cost: 140,
    effect: "自分の燃焼床が近接して閉じた輪を作ると内側も短く燃える。",
  },
  {
    id: "G01",
    name: "冷気付与",
    family: "G",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "武器命中で冷却を付け、敵を少し遅くする。",
  },
  {
    id: "G02",
    name: "霜の波",
    family: "G",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "周期的な冷気の輪を放つ。",
  },
  {
    id: "G03",
    name: "氷針",
    family: "G",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "低速の追尾針で同じ敵に冷却を重ねる。",
  },
  {
    id: "G04",
    name: "凍結閾値",
    family: "G",
    requires_all: ["G01"],
    major: false,
    cost: 25,
    effect: "冷却を重ねると短い凍結。",
  },
  {
    id: "G05",
    name: "氷床",
    family: "G",
    requires_all: ["G02"],
    major: false,
    cost: 25,
    effect: "冷気の輪が通った場所に短い減速領域。",
  },
  {
    id: "G06",
    name: "冷点照準",
    family: "G",
    requires_all: ["G03"],
    major: false,
    cost: 25,
    effect: "氷針が冷却の多い敵を優先。",
  },
  {
    id: "G07",
    name: "脆い結晶",
    family: "G",
    requires_all: ["G04"],
    major: false,
    cost: 60,
    effect: "凍結した敵に次の重い命中の追加ダメージ。",
  },
  {
    id: "G08",
    name: "凍域",
    family: "G",
    requires_all: ["G05"],
    major: false,
    cost: 60,
    effect: "氷床の中で凍結の持続が伸びる。対ボスは冷却維持へ変換。",
  },
  {
    id: "G09",
    name: "凍傷",
    family: "G",
    requires_all: ["G06"],
    major: false,
    cost: 60,
    effect: "冷却が最大の敵に継続ダメージ。",
  },
  {
    id: "G10",
    name: "砕氷",
    family: "G",
    requires_all: ["G07"],
    major: true,
    cost: 140,
    effect: "凍結への重い命中で凍結を消費し、破片が飛ぶ。",
  },
  {
    id: "G11",
    name: "冬眠域",
    family: "G",
    requires_all: ["G08"],
    major: true,
    cost: 140,
    effect: "氷床の敵を長く足止めする代わりに自分の直接攻撃速度が低下。",
  },
  {
    id: "G12",
    name: "永久凍土",
    family: "G",
    requires_all: ["G09"],
    major: true,
    cost: 140,
    effect: "同じ敵への冷却維持で凍傷を強める。敵ごとの上限あり。",
  },
  {
    id: "H01",
    name: "雷石",
    family: "H",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "一定間隔で近くの敵へ落雷。",
  },
  {
    id: "H02",
    name: "帯電",
    family: "H",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "通常命中を数え、一定回数で追加電撃。",
  },
  {
    id: "H03",
    name: "会心核",
    family: "H",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "武器命中に会心判定。",
  },
  {
    id: "H04",
    name: "導電",
    family: "H",
    requires_all: ["H01"],
    major: false,
    cost: 25,
    effect: "落雷が近くの帯電・冷却対象へ一度広がる。",
  },
  {
    id: "H05",
    name: "補給電流",
    family: "H",
    requires_all: ["H02"],
    major: false,
    cost: 25,
    effect:
      "追加電撃が石弾倉の弾を一つ補給。弾倉がない構成では次の通常武器攻撃を少し早める。",
  },
  {
    id: "H06",
    name: "研ぎ澄まし",
    family: "H",
    requires_all: ["H03"],
    major: false,
    cost: 25,
    effect: "同じ敵への連続した非会心命中で次の会心率増。",
  },
  {
    id: "H07",
    name: "避雷印",
    family: "H",
    requires_all: ["H04"],
    major: false,
    cost: 60,
    effect: "最初の落雷で敵に印、次の落雷がその敵を優先。",
  },
  {
    id: "H08",
    name: "電撃加速",
    family: "H",
    requires_all: ["H05"],
    major: false,
    cost: 60,
    effect: "補給または帯電の発動後、短い射撃加速。",
  },
  {
    id: "H09",
    name: "会心落石",
    family: "H",
    requires_all: ["H06"],
    major: false,
    cost: 60,
    effect: "会心が一定回数出ると、その敵に落石。",
  },
  {
    id: "H10",
    name: "雷網",
    family: "H",
    requires_all: ["H07"],
    major: true,
    cost: 140,
    effect: "印のある敵同士を結ぶ短い放電。単体には印の脈動攻撃。",
  },
  {
    id: "H11",
    name: "永続放電",
    family: "H",
    requires_all: ["H08"],
    major: true,
    cost: 140,
    effect: "帯電を頻繁に発動するほど電撃が強まり、無命中で減る。上限あり。",
  },
  {
    id: "H12",
    name: "大会心",
    family: "H",
    requires_all: ["H09"],
    major: true,
    cost: 140,
    effect: "会心判定の一部を低頻度の強い会心へ変える。期待値と分散を調整。",
  },
  {
    id: "I01",
    name: "呪印",
    family: "I",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "武器命中で印を付け、一定時間後にダメージ。",
  },
  {
    id: "I02",
    name: "毒石",
    family: "I",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "毒を重ねる小さな射撃武装。",
  },
  {
    id: "I03",
    name: "侵食視界",
    family: "I",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "近くの敵へ周期的に低い脆弱を付ける。基礎ダメージもある。",
  },
  {
    id: "I04",
    name: "伝染印",
    family: "I",
    requires_all: ["I01"],
    major: false,
    cost: 25,
    effect: "呪いで倒れた敵から近くへ印を渡す。",
  },
  {
    id: "I05",
    name: "毒溜まり",
    family: "I",
    requires_all: ["I02"],
    major: false,
    cost: 25,
    effect: "毒のある敵の撃破で床を残す。ボスには累積命中でも低頻度配置。",
  },
  {
    id: "I06",
    name: "露出",
    family: "I",
    requires_all: ["I03"],
    major: false,
    cost: 25,
    effect: "脆弱の敵に別属性が当たると脆弱を追加。",
  },
  {
    id: "I07",
    name: "呪いの利息",
    family: "I",
    requires_all: ["I04"],
    major: false,
    cost: 60,
    effect: "印の待ち時間が長いほど強くなる。延長回数に上限。",
  },
  {
    id: "I08",
    name: "濃縮毒",
    family: "I",
    requires_all: ["I05"],
    major: false,
    cost: 60,
    effect: "多数の敵へ撒くより、一体の毒スタックを高くできる。",
  },
  {
    id: "I09",
    name: "異常鑑定",
    family: "I",
    requires_all: ["I06"],
    major: false,
    cost: 60,
    effect: "異なる状態異常の種類数に応じて武器命中を強化。",
  },
  {
    id: "I10",
    name: "死の連鎖",
    family: "I",
    requires_all: ["I07"],
    major: true,
    cost: 140,
    effect: "呪いの伝染先へ少量の残り威力も渡す。伝播減衰あり。",
  },
  {
    id: "I11",
    name: "毒の収穫",
    family: "I",
    requires_all: ["I08"],
    major: true,
    cost: 140,
    effect: "定期的に最も濃い毒を消費し、残り継続分を一括ダメージ。",
  },
  {
    id: "I12",
    name: "断罪",
    family: "I",
    requires_all: ["I09"],
    major: true,
    cost: 140,
    effect: "複数状態の敵に、周期的な重い処刑攻撃。ボス即死にはしない。",
  },
  {
    id: "J01",
    name: "再生拍動",
    family: "J",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "周期的な小回復。満タン時も回復試行イベントを出す。",
  },
  {
    id: "J02",
    name: "石の防壁",
    family: "J",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "一定時間ごとに小さな吸収防壁。",
  },
  {
    id: "J03",
    name: "血の契約",
    family: "J",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "武器の攻撃時に少量HPを使い火力を上げる。HP下限では停止。",
  },
  {
    id: "J04",
    name: "癒しの棘",
    family: "J",
    requires_all: ["J01"],
    major: false,
    cost: 25,
    effect: "回復試行で近くの一体へ小さな追撃。",
  },
  {
    id: "J05",
    name: "防壁反撃",
    family: "J",
    requires_all: ["J02"],
    major: false,
    cost: 25,
    effect: "防壁が攻撃を受けると小さな衝撃波。",
  },
  {
    id: "J06",
    name: "吸血",
    family: "J",
    requires_all: ["J03"],
    major: false,
    cost: 25,
    effect: "通常武器の有効ダメージの一部を回復。毎秒上限あり。",
  },
  {
    id: "J07",
    name: "過剰回復",
    family: "J",
    requires_all: ["J04"],
    major: false,
    cost: 60,
    effect: "溢れた回復量の一部を防壁へ変える。",
  },
  {
    id: "J08",
    name: "蓄痛",
    family: "J",
    requires_all: ["J05"],
    major: false,
    cost: 60,
    effect: "実際に失ったHPを短時間だけ蓄える。",
  },
  {
    id: "J09",
    name: "瀕死の力",
    family: "J",
    requires_all: ["J06"],
    major: false,
    cost: 60,
    effect: "HPが低いほど火力が増す。上限あり。",
  },
  {
    id: "J10",
    name: "治癒爆心",
    family: "J",
    requires_all: ["J07"],
    major: true,
    cost: 140,
    effect: "回復量を蓄え、閾値で近距離の攻撃を放つ。",
  },
  {
    id: "J11",
    name: "苦痛解放",
    family: "J",
    requires_all: ["J08"],
    major: true,
    cost: 140,
    effect: "蓄痛を一定周期で放出して反撃。自傷は低い係数で加算。",
  },
  {
    id: "J12",
    name: "血装",
    family: "J",
    requires_all: ["J09"],
    major: true,
    cost: 140,
    effect:
      "低HP帯で受けた回復の一部を短い攻撃力へ変える。回復自体は止めない。",
  },
  {
    id: "K01",
    name: "走行蓄積",
    family: "K",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "一定距離を連続移動すると次の武器命中に追加衝撃。",
  },
  {
    id: "K02",
    name: "不動照準",
    family: "K",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "停止して少し待つと射撃精度と貫通が上がる。",
  },
  {
    id: "K03",
    name: "無傷の歩み",
    family: "K",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "HPを失わない時間で移動と攻撃の小さな強化を蓄える。",
  },
  {
    id: "K04",
    name: "残像杭",
    family: "K",
    requires_all: ["K01"],
    major: false,
    cost: 25,
    effect: "走行蓄積の発動位置に短命の近接分身を残す。",
  },
  {
    id: "K05",
    name: "据え付け",
    family: "K",
    requires_all: ["K02"],
    major: false,
    cost: 25,
    effect: "停止中に射撃間隔を縮め、移動中はその武装の射撃を休止。",
  },
  {
    id: "K06",
    name: "受け流し",
    family: "K",
    requires_all: ["K03"],
    major: false,
    cost: 25,
    effect: "無傷で溜まる一回限りの防護。発動後は再充填待ち。",
  },
  {
    id: "K07",
    name: "旋回刃",
    family: "K",
    requires_all: ["K04"],
    major: false,
    cost: 60,
    effect: "大きく曲がると外側へ短い衝撃刃。方向変化の連打は間隔制限。",
  },
  {
    id: "K08",
    name: "再配置射撃",
    family: "K",
    requires_all: ["K05"],
    major: false,
    cost: 60,
    effect: "停止強化を移動開始後もごく短く持続。",
  },
  {
    id: "K09",
    name: "完全維持",
    family: "K",
    requires_all: ["K06"],
    major: false,
    cost: 60,
    effect: "HP満タンの間だけ、無傷強化の上限が上がる。",
  },
  {
    id: "K10",
    name: "彗星走行",
    family: "K",
    requires_all: ["K07"],
    major: true,
    cost: 140,
    effect: "走行衝撃を前方の接触攻撃へ変える。強制移動はしない。",
  },
  {
    id: "K11",
    name: "攻守交替",
    family: "K",
    requires_all: ["K08"],
    major: true,
    cost: 140,
    effect: "停止で射撃、移動で防壁の再生を早める。",
  },
  {
    id: "K12",
    name: "幻歩",
    family: "K",
    requires_all: ["K09"],
    major: true,
    cost: 140,
    effect: "受け流しの直後に短い加速と周囲の減速。",
  },
  {
    id: "L01",
    name: "金の火花",
    family: "L",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "敵由来のG回収で近くの敵へ追撃。束数で水増ししない。",
  },
  {
    id: "L02",
    name: "金庫石",
    family: "L",
    requires_all: [],
    major: false,
    cost: 10,
    effect: "保有Gに応じて防壁を得る。難易度ごとの上限あり。",
  },
  {
    id: "L03",
    name: "賞金標",
    family: "L",
    requires_all: [],
    major: false,
    cost: 10,
    effect:
      "周期的に危険な敵を標的にし、撃破報酬増。対象には少量の追加ダメージ。",
  },
  {
    id: "L04",
    name: "回収加速",
    family: "L",
    requires_all: ["L01"],
    major: false,
    cost: 25,
    effect: "G回収の直後に短時間だけ攻撃を速める。",
  },
  {
    id: "L05",
    name: "蓄財砲",
    family: "L",
    requires_all: ["L02"],
    major: false,
    cost: 25,
    effect: "保有Gで通常武器を強化。上限付き、Gは消費しない。",
  },
  {
    id: "L06",
    name: "危険手当",
    family: "L",
    requires_all: ["L03"],
    major: false,
    cost: 25,
    effect: "賞金標の対象が少し強くなり、その対象からの報酬が増す。",
  },
  {
    id: "L07",
    name: "回収波",
    family: "L",
    requires_all: ["L04"],
    major: false,
    cost: 60,
    effect: "一定額の戦闘Gを回収すると周囲を攻撃。",
  },
  {
    id: "L08",
    name: "金庫破り",
    family: "L",
    requires_all: ["L05"],
    major: false,
    cost: 60,
    effect: "防壁の破損で金色の破片を放つ。通貨そのものは落とさない。",
  },
  {
    id: "L09",
    name: "賞金連鎖",
    family: "L",
    requires_all: ["L06"],
    major: false,
    cost: 60,
    effect: "標的撃破で次の標的を短時間強調。連続達成で区間報酬増、上限あり。",
  },
  {
    id: "L10",
    name: "黄金旋風",
    family: "L",
    requires_all: ["L07"],
    major: true,
    cost: 140,
    effect: "回収波の直後に短命の金色周回石。",
  },
  {
    id: "L11",
    name: "守銭の要塞",
    family: "L",
    requires_all: ["L08"],
    major: true,
    cost: 140,
    effect: "金庫の防壁が残る間、近くの敵へ周期攻撃。",
  },
  {
    id: "L12",
    name: "大物契約",
    family: "L",
    requires_all: ["L09"],
    major: true,
    cost: 140,
    effect:
      "ボスの強化を受け入れる代わりに、そのボスへの攻撃と報酬増。出現前に固定。",
  },
  {
    id: "X01",
    name: "感電爆燃",
    family: "X",
    requires_all: ["F01", "H01"],
    major: true,
    cost: 90,
    effect: "燃焼中の敵への落雷が燃焼の一部を消費して爆発。",
  },
  {
    id: "X02",
    name: "温度破砕",
    family: "X",
    requires_all: ["F01", "G04"],
    major: true,
    cost: 90,
    effect: "凍結への燃焼付与が凍結を消費し蒸気破裂。",
  },
  {
    id: "X03",
    name: "氷雷導体",
    family: "X",
    requires_all: ["G01", "H04"],
    major: true,
    cost: 90,
    effect: "冷却の多い敵へ電撃が広がりやすくなる。",
  },
  {
    id: "X04",
    name: "毒炎蒸留",
    family: "X",
    requires_all: ["I02", "F01"],
    major: true,
    cost: 90,
    effect: "毒と燃焼の共存で持続する毒霧。発生間隔あり。",
  },
  {
    id: "X05",
    name: "呪毒熟成",
    family: "X",
    requires_all: ["I01", "I08"],
    major: true,
    cost: 90,
    effect: "呪い発動時に毒スタックを参照して追加ダメージ。毒は消費しない。",
  },
  {
    id: "X06",
    name: "会心伝令",
    family: "X",
    requires_all: ["H03", "E01"],
    major: true,
    cost: 90,
    effect: "通常武器の会心で使い魔がその対象へ突撃。",
  },
  {
    id: "X07",
    name: "癒しの軍勢",
    family: "X",
    requires_all: ["J04", "E02"],
    major: true,
    cost: 90,
    effect: "回復追撃の起点を守護者の位置にも分配。威力総量を分配。",
  },
  {
    id: "X08",
    name: "血の雷管",
    family: "X",
    requires_all: ["J03", "D02"],
    major: true,
    cost: 90,
    effect: "自傷で地雷の準備を進める。間隔とHP消費の下限あり。",
  },
  {
    id: "X09",
    name: "衛星砲台",
    family: "X",
    requires_all: ["C01", "D01"],
    major: true,
    cost: 90,
    effect: "砲台の近くを通った衛星から小さな補助射撃。",
  },
  {
    id: "X10",
    name: "彗星衛星",
    family: "X",
    requires_all: ["K01", "C01"],
    major: true,
    cost: 90,
    effect: "走行蓄積を使い、衛星を短時間加速。",
  },
  {
    id: "X11",
    name: "氷結地雷",
    family: "X",
    requires_all: ["D02", "G01"],
    major: true,
    cost: 90,
    effect: "地雷が冷却を付与。凍結相手には起爆を短く待つ。",
  },
  {
    id: "X12",
    name: "引力雷管",
    family: "X",
    requires_all: ["C06", "D02"],
    major: true,
    cost: 90,
    effect: "引力中心の近くの地雷を、吸引終了時に起爆。",
  },
  {
    id: "X13",
    name: "帰還補給",
    family: "X",
    requires_all: ["B02", "A03"],
    major: true,
    cost: 90,
    effect: "帰還刃の受け取りで石弾倉を一部補給。",
  },
  {
    id: "X14",
    name: "装填重力",
    family: "X",
    requires_all: ["A03", "C03"],
    major: true,
    cost: 90,
    effect: "弾倉の再装填開始時にも小さな引力。",
  },
  {
    id: "X15",
    name: "破片感染",
    family: "X",
    requires_all: ["B06", "I01"],
    major: true,
    cost: 90,
    effect: "爆発由来の破片にも呪印を低い係数で付ける。",
  },
  {
    id: "X16",
    name: "呪いの使徒",
    family: "X",
    requires_all: ["E03", "I01"],
    major: true,
    cost: 90,
    effect: "亡響の命中が呪いの待ち時間を少し進める。",
  },
  {
    id: "X17",
    name: "金貨電流",
    family: "X",
    requires_all: ["L01", "H02"],
    major: true,
    cost: 90,
    effect: "戦闘Gの一定額回収でも帯電カウントが進む。",
  },
  {
    id: "X18",
    name: "賞金狙撃",
    family: "X",
    requires_all: ["L03", "A01"],
    major: true,
    cost: 90,
    effect: "貫通石が賞金標・ボスを優先。射線内の雑魚は貫く。",
  },
  {
    id: "X19",
    name: "防壁衛星",
    family: "X",
    requires_all: ["J02", "C01"],
    major: true,
    cost: 90,
    effect: "衛星が一部の敵弾を防壁耐久と引換えに消す。ボス予兆は消さない。",
  },
  {
    id: "X20",
    name: "不動治療",
    family: "X",
    requires_all: ["K02", "J01"],
    major: true,
    cost: 90,
    effect: "停止中は回復周期が速くなるが、回復量は小さくなる。",
  },
  {
    id: "X21",
    name: "疾走焦土",
    family: "X",
    requires_all: ["K04", "F03"],
    major: true,
    cost: 90,
    effect: "残像の攻撃にも燃焼、残像終了時に短い炎床。",
  },
  {
    id: "X22",
    name: "反撃破砕",
    family: "X",
    requires_all: ["J05", "B03"],
    major: true,
    cost: 90,
    effect: "防壁反撃で破砕石の小さな追撃。反撃同士は循環しない。",
  },
  {
    id: "X23",
    name: "侵食投影",
    family: "X",
    requires_all: ["I03", "F01"],
    major: true,
    cost: 90,
    effect: "侵食視界が火種も低い係数で配る。",
  },
  {
    id: "X24",
    name: "遠征菌床",
    family: "X",
    requires_all: ["E04", "I05"],
    major: true,
    cost: 90,
    effect: "使い魔が離れた場所で起こした撃破にも毒溜まり。",
  },
  {
    id: "R01",
    name: "一器入魂",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect:
      "武装一つ以下で通常武器の出力を大幅強化。二つ以上は装備不可。反応効果は残せる。",
  },
  {
    id: "R02",
    name: "百花繚乱",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect: "武装三つで追加攻撃頻度を得る代わりに通常武器の一発威力低下。",
  },
  {
    id: "R03",
    name: "無手の王",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect:
      "通常武装の自動発射を止め、回復・防壁・反撃攻撃を強化。前提として購入した武装の定義は反撃の参照に使える。",
  },
  {
    id: "R04",
    name: "背水",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect:
      "最大HPの一部を出撃中だけ予約し、低HP条件を満たしやすくする。予約前最大HPを条件判定に使う。",
  },
  {
    id: "R05",
    name: "無傷の誓い",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect: "無傷強化を早く得るが、HP被害時は蓄積を全損。",
  },
  {
    id: "R06",
    name: "長命",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect: "召喚・設置を長く残す代わりに再生成が遅い。",
  },
  {
    id: "R07",
    name: "短命",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect: "召喚・設置を短時間で更新する代わりに個々の直接威力低下。",
  },
  {
    id: "R08",
    name: "遅咲き",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect:
      "呪い・時限爆発・蓄熱の待ち時間と威力を増やす。即時攻撃は弱くなる。",
  },
  {
    id: "R09",
    name: "近接誓約",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect: "近い敵への攻撃を強化する代わりに遠い敵への直接ダメージ低下。",
  },
  {
    id: "R10",
    name: "遠征誓約",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect: "遠い敵への攻撃を強化する代わりに近い敵への直接ダメージ低下。",
  },
  {
    id: "R11",
    name: "総力契約",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect:
      "すべての通常敵が少し強くなり、戦闘報酬増。出撃時・難易度開始時に固定。",
  },
  {
    id: "R12",
    name: "二相機関",
    family: "R",
    requires_all: [],
    major: true,
    cost: 140,
    effect: "移動中は召喚・罠、停止中は通常射撃が強い。反対側の出力低下。",
  },
];

export const SKILLS = BASE_SKILLS.map((n) => ({
  ...n,
  special: n.major,
  requires_all: SPECIAL_REQUIREMENTS[n.id] || n.requires_all,
  name: STONE_TEXT[n.id]?.[0] || (n.major ? n.name + "石" : n.name),
  effect: STONE_TEXT[n.id]?.[1] || n.effect,
  cost: n.major ? 0 : n.cost,
}));
export const RECIPES = SKILLS.filter((n) => n.special).map((n, i) => ({
  id: String(i + 1).padStart(2, "0"),
  specialId: n.id,
  name: n.name,
  core: [n.id],
  play: n.effect,
  weakness_and_boss:
    "必要な特性をすべて習得すると自動解放。特殊石は1個だけ装備できます。",
}));
